#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: 247-616-ESP32
//DESCRIPTION: Programme qui gÃ¨re des fonctionnalitÃ©s de base Ã  l'aide d'une base de temps

//HISTORIQUE:
// 2025-11-18, Harold Kouadio: crÃ©ation

//inclusions globales

//DEFINITIONS REQUISES PAR LE MODULE:
//Dependances materielles:

//UART
#define PILOTEUART_TX_PIN 17
#define PILOTEUART_RX_PIN 16
//I2C
#define PILOTEI2C_SDA_PIN 23
#define PILOTEI2C_SCL_PIN 22

// Moteur 
#define MOTEURAVG 1
#define MOTEURAVD 2
#define MOTEURARG 3
#define MOTEURARD 4
#define ADDRESSPCF 0x22

// WIFIUDP
#define WIFI_SSID "Harold-ESP32" 
#define WIFI_PASSWORD "12345678" 
#define LOCAL_PORT 23506
static const IPAddress IPDEST (192,168,20,1);
#define PORTDEST 23506

//ServiceProtocole637
#define SERVICEPROTOCOLE637_PHASE_RECEPTION 0
#define SERVICEPROTOCOLE637_PHASE_TRANSMISSION 1
#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_TRANSMISSIONS_EN_HZ 500.0
#define SERVICEPROTOCOLE637_NOMBRE_DE_DONNEES_MAXIMUM  16
#define SERVICEPROTOCOLE637_DEBUT_DE_TRAME  '$'
#define SERVICEPROTOCOLE637_INSERTION 0x00
#define SERVICEPROTOCOLE637_TEMPS_D_ATTENTE_MAXIMAL_EN_MS 4
#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_LECTURES_EN_HZ 2000.0

#define INFORMATION_DISPONIBLE  1
#define INFORMATION_TRAITEE  0
#define REQUETE_ACTIVE  1
#define REQUETE_TRAITEE 0
#define MODULE_EN_FONCTION 1
#define MODULE_PAS_EN_FONCTION 0


//Dependances logicielles:
#define SERVICETASKSERVER_PERIODE_EN_US (4000L)
#define SERVICEBASEDETEMPS_FREQUENCE_EN_HZ ((1000000L)/SERVICETASKSERVER_PERIODE_EN_US)

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES 6

#define SERVICEWIFIUDP_PHASE_RECEPTION  0
#define SERVICEPROTOCOLE637_PHASE_TRANSMISSION 1
#define SERVICEWIFIUDP_PHASE_TRANSMISSION 2
#define SERVICEPROTOCOLE637_PHASE_RECEPTION 3
#define PROCESSUSTOURDECOM_TRANSMISSION_PHASE 4
#define PROCESSUSTOURDECOM_RECEPTION_PHASE 5



#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES_DANS_LOOP 1
//#define PROCESSUSTACHELENTEDANSLOOP_PHASE 0

//INFORMATION PUBLIQUE:
//Definitions publiques:
//pas de definitions publiques

//Variables publiques:
//pas de variables publiques

//Fonctions publiques:
//pas de fonctions publiques

#endif
