#ifndef PROCESSUSSUIVEURDELIGNE_H
#define PROCESSUSSUIVEURDELIGNE_H

#define PROCESSUSSUIVEURLIGNE_TOURNEADROITE 0
#define PROCESSUSSUIVEURLIGNE_TOURNEAGAUCHE 1
#define PROCESSUSSUIVEURLIGNE_AVANCE        2
#define PROCESSUSSUIVEURLIGNE_ARRET         3
#define PROCESSUSSUIVEURLIGNE_PERDU         4

// STRUCTURE DU PROCESSUS
typedef struct
{
  unsigned char Direction; 

} PROCESSUSSUIVEURDELIGNE;

extern PROCESSUSSUIVEURDELIGNE processusSuiveurDeLigne;

void processusSuiveurDeLigne_initialise(void) ;



#endif